name: pronoxpert
description: "Pronostics sportifs."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.3.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  intl: ^0.18.1
  url_launcher: ^6.2.4
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true